# sisock
# A containerized sisock installation.

# Use an official Python runtime as a parent image
FROM spt3g:36d0c3d

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt .
