version: '3.2'
services:
  # --------------------------------------------------------------------------
  # The sisock library.
  # --------------------------------------------------------------------------
  sisock:
    image: "sisock"
    build: .

  # --------------------------------------------------------------------------
  # Core Components
  # --------------------------------------------------------------------------
  
  # --------------------------------------------------------------------------
  # This service is required by all others (except grafana).
  # --------------------------------------------------------------------------
  sisock-crossbar:
    image: "sisock-crossbar"
    build: ./components/hub/
    depends_on:
      - "sisock"

  # --------------------------------------------------------------------------
  # A bridge between sisock and grafana: read data from sisock and serve it to
  # grafana over HTTP.
  # --------------------------------------------------------------------------
  sisock-http:
    image: "sisock-http"
    build: ./components/grafana_server/
    depends_on:
      - "sisock"

  # --------------------------------------------------------------------------
  # Data node servier: the following three services are for serving local g3
  # files with sisock: a database, a file-scanner, and a file-reader.
  # --------------------------------------------------------------------------
  sisock-g3-file-scanner:
    image: "sisock-g3-file-scanner"
    build: ./components/g3_file_scanner/
    depends_on:
      - "sisock"

  # --------------------------------------------------------------------------
  # Data Node Servers
  # --------------------------------------------------------------------------

#  g3-reader:
#    image: "g3-reader"
#    build: ${SISOCK_DIR}/components/data_node_servers/g3_reader/
#    volumes:
#      - ${SISOCK_HK_DIR}:/data:ro
#      - ./.crossbar:/app/.crossbar
#    environment:
#        SQL_HOST: "database"
#        SQL_USER: "development"
#        SQL_PASSWD: "development"
#        SQL_DB: "files"
#        MAX_POINTS: 1000
#    depends_on:
#      - "sisock-crossbar"
#      - "database"
#      - "g3-file-scanner"
#
#  # --------------------------------------------------------------------------
#  # Data node server: an example that streams system sensor information. This is
#  # an example that doesn't require any special hardware or external files.
#  # --------------------------------------------------------------------------
#  sensors-server:
#    image: "sensors-server"
#    container_name: sensors-server
#    build: ${SISOCK_DIR}/components/data_node_servers/sensors/
#    volumes:
#      - ./.crossbar:/app/.crossbar
#    depends_on:
#      - "sisock-crossbar"
#
#  # --------------------------------------------------------------------------
#  # Data node server: an example weather server that doesn't require any
#  # special hardware or external files (it comes with its own data files).
#  # --------------------------------------------------------------------------
#  weather-server:
#    image: "weather-server"
#    container_name: weather-server
#    build: ${SISOCK_DIR}/components/data_node_servers/weather/
#    depends_on:
#      - "sisock-crossbar"
#
#  # --------------------------------------------------------------------------
#  # Data node server: serves radiometer data stored on the local machine.
#  # --------------------------------------------------------------------------
#  radiometer-server:
#    image: "radiometer-server"
#    container_name: radiometer-server
#    build: ${SISOCK_DIR}/components/data_node_servers/radiometer/
#    environment:
#        MAX_POINTS: 1000
#    volumes:
#      - ${SISOCK_RADIOMETER_DIR}:/data:ro
#      - ./.crossbar:/app/.crossbar
#    depends_on:
#      - "sisock-crossbar"
#
#  # --------------------------------------------------------------------------
#  # Data node server: serves APEX data stored on the local machine.
#  # --------------------------------------------------------------------------
#  apex-weather-server:
#    image: "apex-weather-server"
#    container_name: apex-weather-server
#    build: ${SISOCK_DIR}/components/data_node_servers/apex_weather/
#    environment:
#        MAX_POINTS: 1000
#    volumes:
#      - ${SISOCK_APEX_DIR}:/data:ro
#      - ./.crossbar:/app/.crossbar
#    depends_on:
#      - "sisock-crossbar"
#
#  # --------------------------------------------------------------------------
#  # Data node server: LS372 measurement.
#  # --------------------------------------------------------------------------
#  ls372-measurement:
#    image: "ls372-measurement"
#    container_name: ls372-measurement
#    build: ${SISOCK_DIR}/components/data_node_servers/thermometry/
#    environment:
#        TARGET: measurement # Match to instance-id of agent to monitor, used
#                            # for data feed subscription.
#        NAME: 'LSA22HA' # Will appear in sisock a front of field name.
#        DESCRIPTION: "LS372 measuring test board in the lab."
#    volumes:
#      - ./.crossbar:/app/.crossbar
#    depends_on:
#      - "sisock-crossbar"
