version: '3.2'
services:
  sisock:
    image: "sisock"
    build: .
  sisock_crossbar:
    image: "sisock_crossbar"
    container_name: sisock_crossbar
    build: ./components/hub/
    ports:
     - "8080:8080"
     - "8001:8001"
    environment:
         - PYTHONUNBUFFERED=1
    depends_on:
      - "sisock"
  sisock_grafana_http:
    image: "sisock_grafana_http"
    container_name: sisock_grafana_http
    build: ./components/grafana_server/
    ports:
     - "5000:5000"
    depends_on:
      - "sisock_crossbar"
  weather_server:
    image: "weather_server"
    container_name: weather_server
    build: ./components/data_node_servers/weather/
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  radiometer_server:
    image: "radiometer_server"
    container_name: radiometer_server
    build: ./components/data_node_servers/radiometer/
    volumes:
      - type: "bind"
        source: "/var/www/Skymonitor"
        target: "/data"
        read_only: true
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  apex_weather_server:
    image: "apex_weather_server"
    container_name: apex_weather_server
    build: ./components/data_node_servers/apex_weather/
    volumes:
      - type: "bind"
        source: "/var/www/apex_weather"
        target: "/data"
        read_only: true
    environment:
        MAX_POINTS: 1000
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  sensors_server:
    image: "sensors_server"
    container_name: sensors_server
    build: ./components/data_node_servers/sensors/
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  ls372_measurement:
    image: "ls372_measurement"
    container_name: ls372_measurement
    build: ./components/data_node_servers/thermometry/
    environment:
        TARGET: measurement # match to instance-id of agent to monitor, used for data feed subscription
        NAME: 'LSA22HA' # will appear in sisock a front of field name
        DESCRIPTION: "LS372 measuring test board in the lab."
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  ls372_control:
    image: "ls372_control"
    container_name: ls372_control
    build: ./components/data_node_servers/thermometry/
    environment:
        TARGET: control # match to instance-id of agent to monitor, used for data feed subscription
        NAME: 'LSA22YG' # will appear in sisock a front of field name
        DESCRIPTION: "LS372 simulating control unit in the lab."
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  ls240_monitor:
    image: "ls240_monitor"
    container_name: ls240_monitor
    build: ./components/data_node_servers/thermometry/
    environment:
        TARGET: test240 # match to instance-id of agent to monitor, used for data feed subscription
        NAME: 'LSA21OQ' # will appear in sisock a front of field name
        DESCRIPTION: "LS240 unit in the lab."
    depends_on:
      - "sisock_crossbar"
      - "sisock_grafana_http"
  #grafana/grafana:
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    - GF_INSTALL_PLUGINS=grafana-simple-json-datasource, natel-plotly-panel

networks:
  default:
    external:
      name: sisock-net
