
build :
	docker build -t g3-reader .
	docker tag g3-reader:latest grumpy.physics.yale.edu/dans-g3-reader:latest

tag :
	docker tag g3-reader:latest grumpy.physics.yale.edu/dans-g3-reader:latest

# vim: set expandtab!:
