
build :
	docker build -t g3-file-scanner .
	docker tag g3-file-scanner:latest grumpy.physics.yale.edu/sisock-g3-file-scanner:latest

tag :
	docker tag g3-file-scanner:latest grumpy.physics.yale.edu/sisock-g3-file-scanner:latest

# vim: set expandtab!:
