
build :
	docker build -t dans-ucsc-radiometer .
	docker tag dans-ucsc-radiometer:latest grumpy.physics.yale.edu/dans-ucsc-radiometer:latest

tag :
	docker tag dans-ucsc-radiometer:latest grumpy.physics.yale.edu/dans-ucsc-radiometer:latest

# vim: set expandtab!:
